(ns clojure-euler.exercise-002
  (:gen-class))


;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;; By starting with 1 and 2, the first 10 terms will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million,
;; find the sum of the even-valued terms.

(defn euler-002 [limit]
  (loop [first 1 second 1 even-sum 0]
    (let [next-val (+ first second)]
      (if (> next-val limit)
        even-sum
        (recur next-val
               first
               (if (even? next-val)
                 (+ even-sum next-val)
                 even-sum))))))